#!/usr/bin/env bash
# Copyright (c) 2026 Capgemini Engineering Research and Development.
#
# This file is part of OCCT-Light software library.
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License version 3 as published
# by the Free Software Foundation, with an option to use any later version.
# Consult the file LICENSE_AGPL_30.txt included in OCCT-Light distribution
# for complete text of the license and disclaimer of any warranty.
#
# Alternatively, this file may be used under the terms of a commercial
# license or contractual agreement.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINDING_DIR="$(dirname "$SCRIPT_DIR")"
EMSDK_DIR="${BINDING_DIR}/.emsdk"
EMSDK_VERSION="${EMSDK_VERSION:-latest}"

echo "[occtl-wasm setup] Target emsdk version: ${EMSDK_VERSION}"
echo "[occtl-wasm setup] Install dir:         ${EMSDK_DIR}"

if [ ! -d "${EMSDK_DIR}" ]; then
  echo "[occtl-wasm setup] Cloning emsdk…"
  git clone --depth 1 https://github.com/emscripten-core/emsdk.git "${EMSDK_DIR}"
fi

cd "${EMSDK_DIR}"
git pull --ff-only || true

./emsdk install "${EMSDK_VERSION}"
./emsdk activate "${EMSDK_VERSION}"

cat > "${SCRIPT_DIR}/emsdk_env.sh" <<EOF
# Generated by bindings/wasm/scripts/setup.sh — \`source\` this before running emcmake.
source "${EMSDK_DIR}/emsdk_env.sh"
EOF

echo
echo "[occtl-wasm setup] Done."
echo
echo "Next steps:"
echo "  source ${SCRIPT_DIR}/emsdk_env.sh"
echo "  (cd ${BINDING_DIR}/../.. && python3 tools/abi_dump.py --output build/abi.json)"
echo "  (cd ${BINDING_DIR} && npm install && npm run generate)"
echo "  emcmake cmake -S ${BINDING_DIR} -B ${BINDING_DIR}/build -DOCCTL_BUILD_BINDINGS_WASM=ON"
echo "  emmake make -C ${BINDING_DIR}/build -j"
