#!/usr/bin/env python3
# Copyright (c) 2026 Capgemini Engineering Research and Development.
#
# This file is part of OCCT-Light software library.
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License version 3 as published
# by the Free Software Foundation, with an option to use any later version.
# Consult the file LICENSE_AGPL_30.txt included in OCCT-Light distribution
# for complete text of the license and disclaimer of any warranty.
#
# Alternatively, this file may be used under the terms of a commercial
# license or contractual agreement.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Generate the Java/JNA raw layer from build/abi.json.

Outputs:
- src/main/java/org/occtl/generated/OcctlTypes.java
- src/main/java/org/occtl/generated/OcctlRawLibrary.java
- src/main/java/org/occtl/generated/OcctlGenerated.java
- src/main/java/org/occtl/generated/OcctlTyped.java
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

COPYRIGHT = """// Copyright (c) 2026 Capgemini Engineering Research and Development.
//
// This file is part of OCCT-Light software library.
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License version 3 as published
// by the Free Software Foundation, with an option to use any later version.
// Consult the file LICENSE_AGPL_30.txt included in OCCT-Light distribution
// for complete text of the license and disclaimer of any warranty.
//
// Alternatively, this file may be used under the terms of a commercial
// license or contractual agreement.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//"""
GENERATED = "// <auto-generated>This file was emitted by bindings/java/tools/generate_facade.py — do not edit.</auto-generated>"

PRIM_MAP: dict[str, str] = {
    "void": "void",
    "char": "byte",
    "signed char": "byte",
    "unsigned char": "byte",
    "short": "short",
    "unsigned short": "short",
    "int": "int",
    "unsigned int": "int",
    "long": "long",
    "unsigned long": "long",
    "long long": "long",
    "unsigned long long": "long",
    "float": "float",
    "double": "double",
    "size_t": "NativeLong",
    "ssize_t": "NativeLong",
    "ptrdiff_t": "NativeLong",
    "int8_t": "byte",
    "uint8_t": "byte",
    "int16_t": "short",
    "uint16_t": "short",
    "int32_t": "int",
    "uint32_t": "int",
    "int64_t": "long",
    "uint64_t": "long",
    "_Bool": "int",
    "bool": "int",
}

PRIM_BYREF_MAP: dict[str, str] = {
    "int": "IntByReference",
    "unsigned int": "IntByReference",
    "int32_t": "IntByReference",
    "uint32_t": "IntByReference",
    "short": "ShortByReference",
    "unsigned short": "ShortByReference",
    "int16_t": "ShortByReference",
    "uint16_t": "ShortByReference",
    "long": "LongByReference",
    "unsigned long": "LongByReference",
    "long long": "LongByReference",
    "unsigned long long": "LongByReference",
    "int64_t": "LongByReference",
    "uint64_t": "LongByReference",
    "size_t": "NativeLongByReference",
    "ssize_t": "NativeLongByReference",
    "ptrdiff_t": "NativeLongByReference",
    "double": "DoubleByReference",
    "float": "FloatByReference",
    "byte": "ByteByReference",
    "char": "ByteByReference",
    "signed char": "ByteByReference",
    "unsigned char": "ByteByReference",
}


class AbiModel:
    def __init__(self, abi: dict[str, Any]) -> None:
        self.abi = abi
        self.types_by_name: dict[str, dict[str, Any]] = {}
        for t in abi["types"]:
            self.types_by_name[t["name"]] = t
        self.enum_names: set[str] = set()
        self.struct_names: set[str] = set()
        self.value_handle_names: set[str] = set()
        self.opaque_names: set[str] = set()
        self.alias_names: set[str] = set()
        for t in abi["types"]:
            kind = t["kind"]
            name = t["name"]
            if kind == "enum":
                self.enum_names.add(name)
            elif kind == "struct":
                self.struct_names.add(name)
            elif kind == "value_handle":
                self.value_handle_names.add(name)
            elif kind == "opaque_handle":
                self.opaque_names.add(name)
            elif kind == "alias":
                self.alias_names.add(name)

        self.callback_aliases: dict[str, tuple[str, str]] = {}
        for t in abi["types"]:
            if t["kind"] != "alias":
                continue
            u = t.get("underlying", "")
            m = re.match(r"\s*occtl_status_t\s*\(\s*\*\s*\)\s*\(([^,]+),\s*void\s*\*\s*\)\s*$", u)
            if not m:
                continue
            first = m.group(1).strip()
            self.callback_aliases[t["name"]] = (java_struct_class(first), first)



def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def java_struct_class(c_name: str) -> str:
    base = c_name.strip()
    if base.endswith("_t"):
        base = base[:-2]
    parts = [p for p in base.split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def java_ident(name: str) -> str:
    out = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if re.match(r"^[0-9]", out):
        out = f"_{out}"
    keywords = {
        "class", "interface", "enum", "public", "private", "protected", "static", "final",
        "native", "new", "return", "package", "import", "int", "long", "float", "double",
        "void", "short", "byte", "char", "boolean", "if", "else", "switch", "case", "default",
        "while", "for", "do", "try", "catch", "finally", "throw", "throws", "null", "true", "false",
    }
    if out in keywords:
        out = f"{out}_"
    return out


def strip_qualifiers(c_type: str) -> str:
    s = c_type
    s = re.sub(r"\bconst\b", " ", s)
    s = re.sub(r"\bvolatile\b", " ", s)
    s = re.sub(r"\brestrict\b", " ", s)
    s = re.sub(r"\b_Nullable\b", " ", s)
    s = re.sub(r"\b_Nonnull\b", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def parse_type(c_type: str) -> tuple[str, int]:
    s = strip_qualifiers(c_type)
    ptr = s.count("*")
    base = s.replace("*", " ")
    base = re.sub(r"\s+", " ", base).strip()
    return base, ptr


def parse_field_type(c_type: str) -> tuple[str, int, int | None]:
    s = strip_qualifiers(c_type)
    m = re.match(r"^(.*?)(\[[0-9]+\](?:\[[0-9]+\])*)$", s)
    if not m:
        base, ptr = parse_type(c_type)
        return base, ptr, None
    base = m.group(1).strip()
    dims = [int(x) for x in re.findall(r"\[([0-9]+)\]", m.group(2))]
    arr_size = 1
    for d in dims:
        arr_size *= d
    base, ptr = parse_type(base)
    return base, ptr, arr_size


def java_param_type(model: AbiModel, c_type: str) -> str:
    base, ptr = parse_type(c_type)
    if ptr >= 2:
        return "PointerByReference"
    if ptr == 1:
        if base in model.value_handle_names or base in model.struct_names:
            return "Pointer"
        if base in model.callback_aliases:
            return f"OcctlTypes.{java_struct_class(base)}"
        if base in model.enum_names:
            return "IntByReference"
        if base in PRIM_BYREF_MAP:
            return PRIM_BYREF_MAP[base]
        return "Pointer"

    if base in model.callback_aliases:
        return f"OcctlTypes.{java_struct_class(base)}"
    if base in PRIM_MAP:
        return PRIM_MAP[base]
    if base in model.opaque_names:
        return "Pointer"
    if base in model.enum_names:
        return "int"
    if base in model.value_handle_names:
        return "long"
    if base in model.struct_names:
        return "Pointer"
    if base in model.alias_names:
        t = model.types_by_name[base]
        ubase, uptr = parse_type(t.get("underlying", ""))
        if "(*" in t.get("underlying", ""):
            return f"OcctlTypes.{java_struct_class(base)}"
        if uptr == 0 and (ubase in model.value_handle_names or ubase in model.struct_names):
            return f"OcctlTypes.{java_struct_class(ubase)}.ByValue"
    return "Pointer"


def java_return_type(model: AbiModel, c_type: str) -> str:
    base, ptr = parse_type(c_type)
    if ptr > 0:
        return "Pointer"
    if base in PRIM_MAP:
        return PRIM_MAP[base]
    if base in model.enum_names:
        return "int"
    if base in model.opaque_names:
        return "Pointer"
    if base in model.value_handle_names:
        return "long"
    if base in model.struct_names:
        return "Pointer"
    if base in model.alias_names:
        t = model.types_by_name[base]
        ubase, uptr = parse_type(t.get("underlying", ""))
        if uptr == 0 and (ubase in model.value_handle_names or ubase in model.struct_names):
            return f"OcctlTypes.{java_struct_class(ubase)}.ByValue"
    return "Pointer"


def field_java_type(model: AbiModel, c_type: str) -> tuple[str, int | None]:
    base, ptr, arr_size = parse_field_type(c_type)
    if ptr > 0:
        return ("Pointer", arr_size)
    if base in PRIM_MAP:
        return (PRIM_MAP[base], arr_size)
    if base in model.enum_names:
        return ("int", arr_size)
    if base in model.value_handle_names or base in model.struct_names:
        return (f"OcctlTypes.{java_struct_class(base)}", arr_size)
    if base in model.opaque_names:
        return ("Pointer", arr_size)
    if base in model.alias_names:
        t = model.types_by_name[base]
        ubase, uptr = parse_type(t.get("underlying", ""))
        if uptr == 0 and (ubase in model.value_handle_names or ubase in model.struct_names):
            return (f"OcctlTypes.{java_struct_class(ubase)}", arr_size)
    return ("Pointer", arr_size)


def collect_struct_types(model: AbiModel) -> list[dict[str, Any]]:
    picked: dict[str, dict[str, Any]] = {}
    for t in model.abi["types"]:
        if t["kind"] not in {"struct", "value_handle"}:
            continue
        name = t["name"]
        if not name.endswith("_t"):
            continue
        picked[name] = t
    return [picked[n] for n in sorted(picked.keys())]


def collect_callback_aliases(model: AbiModel) -> list[str]:
    return sorted(model.callback_aliases.keys())


def render_types(model: AbiModel) -> str:
    out: list[str] = [COPYRIGHT, GENERATED, "package org.occtl.generated;", "", "import java.util.List;", "import com.sun.jna.Callback;", "import com.sun.jna.NativeLong;", "import com.sun.jna.Pointer;", "import com.sun.jna.Structure;", "", "public final class OcctlTypes {", "    private OcctlTypes() {}", ""]

    # Callback aliases first.
    for alias in collect_callback_aliases(model):
        class_name = java_struct_class(alias)
        value_cls, value_c_type = model.callback_aliases[alias]
        if value_c_type in model.value_handle_names:
            callback_arg = "long"
        else:
            callback_arg = f"{value_cls}.ByValue"
        out.append(f"    public interface {class_name} extends Callback {{")
        out.append(f"        int invoke({callback_arg} value, Pointer userData);")
        out.append("    }")
        out.append("")

    for t in collect_struct_types(model):
        c_name = t["name"]
        class_name = java_struct_class(c_name)
        fields = t.get("fields", [])
        out.append("    @Structure.FieldOrder({")
        if fields:
            for i, f in enumerate(fields):
                comma = "," if i + 1 < len(fields) else ""
                out.append(f"        \"{f['name']}\"{comma}")
        out.append("    })")
        out.append(f"    public static class {class_name} extends Structure {{")
        out.append(f"        public static class ByReference extends {class_name} implements Structure.ByReference {{}}")
        out.append(f"        public static class ByValue extends {class_name} implements Structure.ByValue {{}}")
        out.append(f"        public {class_name}() {{ super(); }}")
        out.append(f"        public {class_name}(Pointer p) {{ super(p); read(); }}")

        if t["kind"] == "value_handle":
            out.append("        public long bits;")
        else:
            for f in fields:
                f_java, arr = field_java_type(model, f["type"])
                f_name = java_ident(f["name"])
                if arr is not None:
                    if f_java in {"byte", "short", "int", "long", "float", "double"}:
                        out.append(f"        public {f_java}[] {f_name} = new {f_java}[{arr}];")
                    else:
                        # Fallback for non-primitive arrays in rare layouts.
                        out.append(f"        public {f_java} {f_name};")
                else:
                    out.append(f"        public {f_java} {f_name};")
        out.append("    }")
        out.append("")

    out.append("}")
    out.append("")
    return "\n".join(out)


def render_constants(model: AbiModel) -> str:
    out: list[str] = [COPYRIGHT, GENERATED, "package org.occtl.generated;", "", "import java.util.ArrayList;", "import java.util.Collections;", "import java.util.List;", "", "public final class OcctlGenerated {", "    private OcctlGenerated() {}", "", f"    public static final int ABI_VERSION = {int(model.abi.get('abi_version') or 0)};", ""]

    constants = model.abi.get("constants") or []
    numeric: list[tuple[str, str]] = []
    for c in constants:
        name = c["name"]
        val = c.get("value")
        if isinstance(val, (int, float)):
            numeric.append((name, repr(val)))
            continue
        if isinstance(val, str) and re.fullmatch(r"-?[0-9]+", val.strip()):
            numeric.append((name, val.strip()))
            continue

    for name, val in sorted(numeric):
        jname = java_ident(name)
        out.append(f"    public static final long {jname} = {val}L;")

    enum_values: dict[str, int] = {}
    for t in model.abi["types"]:
        if t.get("kind") != "enum":
            continue
        if t.get("name", "").endswith("_t"):
            continue
        for value in t.get("values", []):
            enum_values[value["name"]] = int(value["value"])
    if enum_values:
        out.append("")
        for name, value in sorted(enum_values.items()):
            out.append(f"    public static final int {java_ident(name)} = {value};")

    out.append("")
    out.append("    public static final List<String> EXPORTED_FUNCTIONS;")
    out.append("    static {")
    out.append("        ArrayList<String> names = new ArrayList<>();")
    for fn in sorted(model.abi["functions"], key=lambda x: x["name"]):
        out.append(f"        names.add(\"{fn['name']}\");")
    out.append("        EXPORTED_FUNCTIONS = Collections.unmodifiableList(names);")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def render_raw_library(model: AbiModel) -> str:
    out: list[str] = [
        COPYRIGHT,
        GENERATED,
        "package org.occtl.generated;",
        "",
        "import com.sun.jna.Library;",
        "import com.sun.jna.Native;",
        "import com.sun.jna.NativeLong;",
        "import com.sun.jna.Pointer;",
        "import com.sun.jna.ptr.*;",
        "",
        "public interface OcctlRawLibrary extends Library {",
        "    static OcctlRawLibrary load(String libName) {",
        "        return Native.load(libName, OcctlRawLibrary.class);",
        "    }",
        "",
    ]

    for fn in sorted(model.abi["functions"], key=lambda x: x["name"]):
        ret = java_return_type(model, fn["return_type"])
        params: list[str] = []
        for p in fn["params"]:
            p_type = java_param_type(model, p["type"])
            p_name = java_ident(p["name"] or "arg")
            params.append(f"{p_type} {p_name}")
        sig = ", ".join(params)
        out.append(f"    {ret} {fn['name']}({sig});")

    out.append("}")
    out.append("")
    return "\n".join(out)


def render_typed_layer(model: AbiModel) -> str:
    out: list[str] = [
        COPYRIGHT,
        GENERATED,
        "package org.occtl.generated;",
        "",
        "import com.sun.jna.NativeLong;",
        "import com.sun.jna.Pointer;",
        "import com.sun.jna.ptr.*;",
        "",
        "import org.occtl.OcctL;",
        "",
        "public final class OcctlTyped {",
        "    private final OcctlRawLibrary raw;",
        "",
        "    public OcctlTyped(OcctlRawLibrary raw) {",
        "        this.raw = raw;",
        "    }",
        "",
    ]

    for fn in sorted(model.abi["functions"], key=lambda x: x["name"]):
        ret = java_return_type(model, fn["return_type"])
        params: list[str] = []
        args: list[str] = []
        for p in fn["params"]:
            p_type = java_param_type(model, p["type"])
            p_name = java_ident(p["name"] or "arg")
            params.append(f"{p_type} {p_name}")
            args.append(p_name)
        sig = ", ".join(params)
        call = f"raw.{fn['name']}({', '.join(args)})"

        # Typed layer: status-returning functions become checked void methods.
        if fn["return_type"] == "occtl_status_t":
            out.append(f"    public void {fn['name']}({sig}) {{")
            out.append(f"        OcctL.check({call});")
            out.append("    }")
            out.append("")
        else:
            out.append(f"    public {ret} {fn['name']}({sig}) {{")
            if ret == "void":
                out.append(f"        {call};")
            else:
                out.append(f"        return {call};")
            out.append("    }")
            out.append("")

    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Java/JNA facade from abi.json")
    parser.add_argument("--abi", type=Path, required=True, help="Path to build/abi.json")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "main" / "java" / "org" / "occtl" / "generated",
        help="Output directory for generated Java sources",
    )
    args = parser.parse_args()

    abi = json.loads(args.abi.read_text(encoding="utf-8"))
    model = AbiModel(abi)

    write(args.out / "OcctlTypes.java", render_types(model))
    write(args.out / "OcctlGenerated.java", render_constants(model))
    write(args.out / "OcctlRawLibrary.java", render_raw_library(model))
    write(args.out / "OcctlTyped.java", render_typed_layer(model))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
